### ISSUE TITLE
Sound Shader

### ISSUE THREAD

**Issue by fand** [fand/veda#59]
from v2.3.0, VEDA started to support sound shaders:
https://twitter.com/amagitakayosi/status/949875869681516544

# TODO
- [x] Add `loadSoundShader()` to `vedajs`
- [x] Load samples as textures
- Fix bugs
  - [ ] Avoid shaders evaluated twice on settings change
  - [ ] Full sound not rendered until `alt-enter` runs twice
- [ ] Add document to [veda.gl](https://github.com/fand/veda.gl)
